apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  dashboard.json: |-
{{ .Files.Get "dashboard.json" | indent 4}}
  dashboard-provider.yml: |-
{{ .Files.Get "dashboard-provider.yml" | indent 4}}
  datasource.yaml: |-
{{ .Files.Get "datasource.yaml" | indent 4}}