apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-chart.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
{{ include "grafana-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "grafana-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
